### ISSUE TITLE
Failed to activate package named 'markdown-format' Error: JavaScript error: Cannot find module 'syscall'

### ISSUE THREAD

**Issue by devfoo-one** [shurcooL/atom-markdown-format#10]
Hi,

after updating atom to 0.138.0 markdown format does not work anymore.
The Console says:

```
Failed to activate package named 'markdown-format' Error: JavaScript error: Cannot find module 'syscall'
```

in

```
/Applications/Atom.app/Contents/Resources/app/src/package.js:204
```
